"""Native Hold'em mechanics + compact-v2 encoder parity (Phases 8, 11-12).

Random reachable-state corpora are generated by playing the *Python* release
game; every state is replayed into the native backend (debug API) and all
observable mechanics are compared:

current player, terminal/chance flags, legal actions (tokens AND order),
pot, contributions, street, fold/all-in status, terminal utility, and the
full infoset key string (which simultaneously proves the native packed key
neither merges distinct Python infosets nor splits merged ones — the
packing is bijective per config).
"""

from __future__ import annotations

import numpy as np
import pytest

from poker_alpha.solver_config import RELEASE_CONFIG, PRIMARY_CONFIG

from native_helpers import native_cfg, native_info, random_state_corpus

CORPUS_HANDS_FAST = 400
CORPUS_HANDS_SLOW = 2500


def _compare_state(game, ncfg, state):
    info = native_info(ncfg, state)
    assert info["is_terminal"] == game.is_terminal(state)
    assert info["is_chance"] == game.is_chance(state)
    assert info["folded"] == state.folded
    assert info["all_in"] == state.all_in
    assert info["street"] == len(state.streets) - 1
    c = info["contrib"]
    assert c[0] == state.contrib[0] and c[1] == state.contrib[1]  # bit-equal
    assert info["pot"] == state.pot
    if game.is_terminal(state):
        assert info["utility"] == game.utility(state)
        return
    if game.is_chance(state):
        return
    assert info["current_player"] == game.current_player(state)
    assert list(info["legal_actions"]) == game.legal_actions(state)
    assert info["infoset_key"] == game.infoset_key(state)


def _run_corpus(config, hands, seed):
    ncfg = native_cfg(config)
    n_states = 0
    keys = {}
    for game, state in random_state_corpus(config, hands, seed):
        _compare_state(game, ncfg, state)
        n_states += 1
        if not game.is_terminal(state) and not game.is_chance(state):
            info = native_info(ncfg, state)
            prev = keys.setdefault(int(info["key_u64"]), info["infoset_key"])
            assert prev == info["infoset_key"], "u64 key collision across strings"
    return n_states


def test_release_config_parity_fast():
    n = _run_corpus(RELEASE_CONFIG, CORPUS_HANDS_FAST, seed=7)
    assert n > 2_500


@pytest.mark.slow
def test_release_config_parity_large():
    n = _run_corpus(RELEASE_CONFIG, CORPUS_HANDS_SLOW, seed=11)
    assert n > 15_000


@pytest.mark.slow
def test_v1_config_parity():
    """The v1 game (no preflop multiples, no min-raise) shares the code path."""
    n = _run_corpus(PRIMARY_CONFIG, 800, seed=13)
    assert n > 4_500


# -- scripted edge cases ----------------------------------------------------

def _play(config, tokens, rng_seed=0):
    """Play explicit decision tokens, sampling chance with a seeded rng;
    yields every intermediate state."""
    game = config.build_game()
    rng = np.random.default_rng(rng_seed)
    state = game.root()
    yield game, state
    it = iter(tokens)
    while True:
        if game.is_terminal(state):
            return
        if game.is_chance(state):
            state = game.sample_chance(state, rng)
        else:
            tok = next(it, None)
            if tok is None:
                return
            assert tok in game.legal_actions(state), (tok, game.legal_actions(state))
            state = game.next_state(state, tok)
        yield game, state


EDGE_LINES = [
    ["c", "c", "c", "c", "c", "c", "c", "c"],            # limp, check it down
    ["f"],                                                  # instant fold
    ["x200", "f"],                                          # open, fold
    ["x200", "x250", "c"],                                  # 3-bet call
    ["x200", "x250", "x350", "c"],                          # raise-cap preflop
    ["x200", "a", "c"],                                     # all-in call, runout
    ["x200", "a", "f"],                                     # all-in fold
    ["c", "c", "b75", "c", "b75", "b150", "c", "c", "c"],  # postflop raises
    ["c", "c", "c", "b75", "a", "c"],                       # flop bet, shove, call
    ["x350", "x350", "x350", "c"],                          # capped raises, call
    ["x200", "x250", "a", "c"],                             # 3-bet shove call
    ["c", "c", "c", "c", "c", "c", "b150", "a", "f"],      # river shove fold
    ["c", "c", "b150", "b150", "c", "c", "c", "c", "c"],   # big flop raise
]


def test_edge_case_lines():
    ncfg = native_cfg(RELEASE_CONFIG)
    total = 0
    for i, line in enumerate(EDGE_LINES):
        for rng_seed in (0, 1, 2):
            for game, state in _play(RELEASE_CONFIG, line, rng_seed=100 + i * 3 + rng_seed):
                _compare_state(game, ncfg, state)
                total += 1
    assert total > 300


def test_split_pot_utility():
    """Board plays for both -> utility 0 on both backends."""
    from poker_alpha.games.holdem import HoldemState

    config = RELEASE_CONFIG
    game = config.build_game()
    ncfg = native_cfg(config)
    # Royal flush on board; both hole hands irrelevant.
    board = (12 + 39, 11 + 39, 10 + 39, 9 + 39, 8 + 39)
    state = HoldemState(holes=((0, 14), (1, 15)), board=board,
                        streets=("cc", "cc", "cc", "cc"),
                        contrib=(1.0, 1.0))
    assert game.is_terminal(state)
    assert game.utility(state) == 0.0
    _compare_state(game, ncfg, state)
